# -*- coding: utf-8 -*-
"""edprog.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10cGifgtVdRYUxDni0643UGGgfAXwuO1t
"""

import xml.etree.ElementTree as ET
import re
tree = ET.parse('fcdoutput.xml')
root = tree.getroot()

# 最上位階層のタグ・中身
#print(root.tag,root.attrib)
# 子階層のタグ・中身
#for child in root:
#    print(child.tag)
#    print(child.attrib)


import sys
from xml.etree.ElementTree import iterparse
import copy
Ldict={}
timewidth=10
def SUMOTraceParser(FCDOutput):
    t=0
    dict1={}
    doc = iterparse(FCDOutput, events=('start', 'end'))
    # Skip the root element
    event, root =  next(doc)
    for event, elem in doc:
        if event == 'start':
            if elem.tag == 'timestep':
                if t != float(elem.attrib['time']) and (float(elem.attrib['time'])%timewidth)==0:
                    a=copy.copy(dict1)
                    Ldict[t]=a
                    dict1.clear()
                t = float(elem.attrib['time'])
                
            elif elem.tag == 'vehicle':
                lane =elem.attrib['lane']
                lane=lane[:-2]
                if(re.search('A',lane)):
                    m=re.search('A',lane)
                    lane=lane[:m.start()-1]
                lane=re.sub(':','',lane)
                if(re.search('-',lane)):
                    lane=lane[1:]
                if lane in dict1:
                  n=dict1[lane]
                  n=n+1
                  dict1[lane]=n
                else:
                  dict1[lane]=1
                
                            
                
        elif event == 'end':
            if elem.tag == 'timestep':
                Ldict[float(elem.attrib['time'])]=dict1
                elem.clear()
                root.clear()


###
if __name__=='__main__':

    FCDOutput = 'fcdoutput.xml'
    #FCDOutput = 'sumoTrace.txt'
    SUMOTraceParser(FCDOutput)

